plugins {
    id 'java'
    id 'application'
    id 'com.diffplug.spotless' version '7.0.2'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    testImplementation platform("org.junit:junit-bom:6.0.1")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

application {
    mainClass = 'calculator.Main'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

spotless {
    java {
        googleJavaFormat("1.27.0").aosp().reflowLongStrings()
        trimTrailingWhitespace()
        endWithNewline()
    }
}
